pipeline {
    agent any

    tools {
        maven 'Mvn3.9'
        jdk 'JDK-17'
    }

    environment {
        IMAGE_NAME = "abdelrahmangad275/jenkins-app"
    }

    stages {
        stage('Cloning the repo') {
            steps {
                git url: 'https://github.com/AbdullrahmanGad/ivolve-Tasks.git', branch: 'main'
            }
        }

        stage('Run Unit Test') {
            steps {
                dir('Jenkins/pipeline-1') {
                    sh 'mvn test'
                }
            }
        }

        stage('Build the app') {
            steps {
                dir('Jenkins/pipeline-1') {
                    sh 'mvn package'
                }
            }
        }

        stage('Build Docker image') {
            steps {
                dir('Jenkins/pipeline-1') {
                    sh "docker build -t ${IMAGE_NAME}:v${BUILD_NUMBER} ."
                }
            }
        }

        stage('Push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin"
                    sh "docker push ${IMAGE_NAME}:v${BUILD_NUMBER}"
                }
            }
        }

        stage('Update deployment YAML tag') {
            steps {
                dir('Jenkins/pipeline-1') {
                    sh """
                        sed -i 's|IMAGE_TAG|v${BUILD_NUMBER}|g' deployment.yml
                        cat deployment.yaml
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('Jenkins/pipeline-1') {
                    withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                        sh "kubectl --kubeconfig=\$KUBECONFIG apply -f deployment.yml"
                        sh "kubectl --kubeconfig=\$KUBECONFIG rollout status deployment/jenkins-app"
                    }
                }
            }
        }

        stage('Cleanup local image') {
            steps {
                sh "docker rmi ${IMAGE_NAME}:v${BUILD_NUMBER} || true"
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline succeeded!"
            echo "🚀 Deployed image: ${IMAGE_NAME}:v${BUILD_NUMBER}"
        }
        failure {
            echo "❌ Pipeline failed!"
        }
        always {
            cleanWs()
        }
    }
}

